POST http://localhost:3000/api/users/register-user HTTP/1.1
Content-Type: application/json

{
  "name": "test-10",
  "surname": "test-10",
  "password": "Ansik@Asasin98",
  "gender": 0,
  "phone": "7070000010",
  "birthday": "2000/09/19"
}

###

POST http://localhost:3000/api/users/validate HTTP/1.1
Content-Type: application/json

{
  "field": "phone",
  "value": "7086144672"
}

###

GET http://localhost:3000/api/users/authenticate HTTP/1.1
Content-Type: application/json

{
  "phone": "7086144672",
  "password": "Ansik@Asasin98"
}

###

GET http://localhost:3000/api/users/fetch-data HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpcCI6Ijo6ZmZmZjoxMjcuMC4wLjEiLCJyb2xlX2xldmVsIjowLCJwaG9uZSI6IjcwODYxNDQ2NzIiLCJpYXQiOjE1ODgwMzA1NTgsImV4cCI6MTU4ODM5MDU1OH0._xWZwyrHTnJ68x27j6j5C1-EhS1IJmTEMYOfmCj-YUw

###

PUT http://localhost:3000/api/users/update-info HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpcCI6Ijo6ZmZmZjoxMjcuMC4wLjEiLCJyb2xlX2xldmVsIjowLCJwaG9uZSI6IjcwODYxNDQ2NzIiLCJpYXQiOjE1ODgwMzA1NTgsImV4cCI6MTU4ODM5MDU1OH0._xWZwyrHTnJ68x27j6j5C1-EhS1IJmTEMYOfmCj-YUw

{
  "name": "Ansar",
  "surname": "Ryspekov",
  "gender": 1,
  "birthday": "2001/01/19"
}

###

PUT http://localhost:3000/api/users/update-credentials HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpcCI6Ijo6ZmZmZjoxMjcuMC4wLjEiLCJyb2xlX2xldmVsIjowLCJwaG9uZSI6IjcwODYxNDQ2NzIiLCJpYXQiOjE1ODgwMzQwOTgsImV4cCI6MTU4ODM5NDA5OH0.BdxIet3531tgdb5_gVdMs67R6tKiAUYbI7dmtaGuYfQ

{
  "oldPassword": "Ansik@ASASIN98",
  "newPassword": "Ansik@Asasin98"
}
